### Index Method
GET http://localhost:3001/api/subscriptions
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE5Nzg4MTksInN1YiI6NH0.uu4TmrN9eA2FCI3bgTBe0TMGQUiMy80tgSriXOwDNCI

### Successfully Create User
POST http://localhost:3001/api/auth/sign_up
Content-Type: application/json

{
    "first_name": "Daniel6",
    "email": "daniel6@test.com",
    "password": "123456",
    "password_confirmation": "123456"
}

### Successfully Create Subscription
POST http://localhost:3001/api/subscriptions
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE5Nzg4MTksInN1YiI6NH0.uu4TmrN9eA2FCI3bgTBe0TMGQUiMy80tgSriXOwDNCI

{
    "name": "Stan",
    "logo_image": "stan.com",
    "amount": 1800,
    "description": "TV and Movie Streaming Platform",
    "user_id": 1
}

### Unsuccessfully Create Subscription
POST http://localhost:3001/api/subscriptions
Content-Type: application/json

{
    "name": "Stan",
    "logo_image": "stan.com",
    "amount": 1800,
    "description": "TV and Movie Streaming Platform",
    "user_id": "no_id"
}

### Show Subscription 7
GET http://localhost:3001/api/subscriptions/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE5Nzg4MTksInN1YiI6NH0.uu4TmrN9eA2FCI3bgTBe0TMGQUiMy80tgSriXOwDNCI

### Unsuccessfully Show Subscription 1000
GET http://localhost:3001/api/subscriptions/1000

### Update Subscription 7
PUT http://localhost:3001/api/subscriptions/7
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTE5Nzg4MTksInN1YiI6NH0.uu4TmrN9eA2FCI3bgTBe0TMGQUiMy80tgSriXOwDNCI

{
    "logo_image": "Successful update"
}

### Delete Subscription 1
DELETE http://localhost:3001/api/subscriptions/1

### Unsuccessfully delete Subscription 1000
DELETE http://localhost:3001/api/subscriptions/1000

### Sign in with correct user
POST http://localhost:3001/api/auth/sign_in
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "123456"
}

### Sign in with incorrect user
POST http://localhost:3001/api/auth/sign_in
Content-Type: application/json

{
    "email": "daniel@incorrect-test.com",
    "password": "123456incorrect"
}

