# Create User
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "first_name": "Daniel2",
    "email": "daniel2@test.com",
    "password": "123456",
    "password_confirmation": "123456"
}